version: '3.8'
services:
  php:
    build: .
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      DEBUG: 'true'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"
